//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAsso
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportAssoEntities : DbContext
    {
        public SportAssoEntities()
            : base("name=SportAssoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<creneau> creneau { get; set; }
        public virtual DbSet<discipline> discipline { get; set; }
        public virtual DbSet<document> document { get; set; }
        public virtual DbSet<lieu> lieu { get; set; }
        public virtual DbSet<participe> participe { get; set; }
        public virtual DbSet<seance> seance { get; set; }
        public virtual DbSet<section> section { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
