//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAsso
{
    using System;
    using System.Collections.Generic;
    
    public partial class creneau
    {
        public long creneau_id { get; set; }
        public long seance_id { get; set; }
        public System.DateTime heure_debut { get; set; }
        public System.DateTime heure_fin { get; set; }
        public string jour_de_la_semaine { get; set; }
    
        public virtual seance seance { get; set; }
    }
}
