//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAsso
{
    using System;
    using System.Collections.Generic;
    
    public partial class participe
    {
        public long utilisateur_id { get; set; }
        public long seance_id { get; set; }
        public bool a_payer { get; set; }
    
        public virtual seance seance { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
