//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAsso
{
    using System;
    using System.Collections.Generic;
    
    public partial class seance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seance()
        {
            this.participe = new HashSet<participe>();
        }
    
        public long seance_id { get; set; }
        public long encadrant_id { get; set; }
        public long lieu_id { get; set; }
        public long section_id { get; set; }
        public int places_max { get; set; }
        public System.TimeSpan heure_debut { get; set; }
        public System.TimeSpan heure_fin { get; set; }
        public string jour_de_la_semaine { get; set; }
    
        public virtual lieu lieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participe> participe { get; set; }
        public virtual section section { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
